version: "3"

services:
  nwhcp-mongo:
    build:
      context: ../NWHCP-server/db/
      dockerfile: db.dockerfile
    image: annaqzhou/nwhcp-mongo
    container_name: nwhcp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../NWHCP-server/mongoDB:/data/db
    logging:
      driver: none
  nwhcp-sql:
    build:
      context: ../NWHCP-server/db/
      dockerfile: Dockerfile
    image: annaqzhou/nwhcp-sqldb
    container_name: nwhcp-sqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=:blah # change these values
      - MYSQL_DATABASE=:mydatabase
  redis:
    image: redis
  nwhcp-server:
    build:
      context: ../NWHCP-server/organizations/
      dockerfile: Dockerfile
    image: annaqzhou/nwhcp-server
    restart: always
    container_name: nwhcp-server
    expose:
      - "80"
      - "90"
    depends_on:
      - nwhcp-mongo
      - nwhcp-sql
    environment:
      - PORTADDR=:80
      - INTERNAL_PORT=:90
      - DBADDR=nwhcp-mongo:27017
  nwhcp-gateway:
    build:
      context: ../NWHCP-server/gateway/
      dockerfile: Dockerfile
    image: annaqzhou/nwhcp-gateway
    restart: always
    container_name: nwhcp-gateway
    expose:
      - "443"
    depends_on: 
      - nwhcp-sql
      - redis
      - nwhcp-server
    ports:
      - "443:443"
    environment:
      # gateway
      - ADDR=:443
      - SESSIONKEY=:key
      - MYSQL_ROOT_PASSWORD=:blah
      - MYSQL_DATABASE=:mydatabase
      - REDISADDR=:redis:6379
      # - ORGADDR=:
      # need to add letsencrypt stuff
      # - TLSCERT=:
      # - TLSKEY=:
  nwhcp-front-end:
    build:
      context: ../NWHCP-front_end/
      dockerfile: Dockerfile
    image: annaqzhou/nwhcp-frontend
    container_name: nwhcp-frontend
    depends_on:
      - nwhcp-mongo
    restart: always
    ports:
      - "80:80"
  nwhcp-data-cleaning:
    build:
      context: ../NWHCP-data_cleaning/
      dockerfile: Dockerfile
    image: annaqzhou/nwhcp-cleaning
    container_name: nwhcp-cleaning
    depends_on:
      - nwhcp-mongo
      - nwhcp-server
      - nwhcp-gateway
    restart: always
    environment:
      - RED_CAP_API_TOKEN=2E036BFA999B6FB594112D27F524EA92
      - INSERT_ORG_API=http://nwhcp-server:90/api/v1/pipeline-db/poporgs
      - TRUNCATE_ORG_API=http://nwhcp-server:90/api/v1/pipeline-db/truncate

