version: "3"

services:
  nwhcp-mongo:
    image: uwjake/nwhcp-mongo
    container_name: nwhcp-mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - /NWHCP-server/mongoDB:/data/db
    logging:
      driver: none
  nwhcp-server:
    image: uwjake/nwhcp-server
    restart: always
    container_name: nwhcp-server
    expose:
      - "80"
    depends_on:
      - nwhcp-mongo
    environment:
      - PORTADDR=:80
      - DBADDR=nwhcp-mongo:27017
  nwhcp-front-end:
    image: uwjake/nwhcp-front-end
    container_name: nwhcp-front-end
    depends_on:
      - nwhcp-mongo
    restart: always
    ports:
      - "80:80"
  nwhcp-data-cleaning:
    image: uwjake/nwhcp-data-cleaning
    container_name: nwhcp-data-cleaning
    depends_on:
      - nwhcp-mongo
      - nwhcp-server
    restart: always
    environment:
      - RED_CAP_API_TOKEN=2E036BFA999B6FB594112D27F524EA92
      - GET_ALL_ORG_API=http://nwhcp-server/api/v1/orgs
      - INSERT_ORG_API=http://nwhcp-server/api/v1/pipeline-db/poporgs
