version: "3"

services:
  nwhcp-mongo:
    build:
      context: ../NWHCP-server/data/
      dockerfile: db.dockerfile
    image: uwjake/nwhcp-mongo
    container_name: nwhcp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../NWHCP-server/mongoDB:/data/db
    logging:
      driver: none
  nwhcp-server:
    build:
      context: ../NWHCP-server/
      dockerfile: Dockerfile
    image: uwjake/nwhcp-server
    restart: always
    container_name: nwhcp-server
    expose:
      - "80"
      - "90"
    depends_on:
      - nwhcp-mongo
    environment:
      - PORTADDR=:80
      - INTERNAL_PORT=:90
      - DBADDR=nwhcp-mongo:27017
  nwhcp-front-end:
    build:
      context: ../NWHCP-front_end/
      dockerfile: Dockerfile
    image: uwjake/nwhcp-front-end
    container_name: nwhcp-front-end
    depends_on:
      - nwhcp-mongo
    restart: always
    ports:
      - "80:80"
  nwhcp-data-cleaning:
    build:
      context: ../NWHCP-data_cleaning/
      dockerfile: Dockerfile
    image: uwjake/nwhcp-data-cleaning
    container_name: nwhcp-data-cleaning
    depends_on:
      - nwhcp-mongo
      - nwhcp-server
    restart: always
    environment:
      - RED_CAP_API_TOKEN=2E036BFA999B6FB594112D27F524EA92
      - INSERT_ORG_API=http://nwhcp-server:90/api/v1/pipeline-db/poporgs
      - TRUNCATE_ORG_API=http://nwhcp-server:90/api/v1/pipeline-db/truncate

