version: "3"

services:
  nwhcp-mongo:
    build:
      context: ../NWHCP-server/data/
      dockerfile: db.dockerfile
    restart: always
    expose:
      - "27017"
    volumes:
      - ../NWHCP-server/mongoDB:/data/db
    logging:
      driver: none
  nwhcp-server:
    build:
      context: ../NWHCP-server/
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    depends_on:
      - nwhcp-mongo
    environment:
      - PORTADDR=:80
      - DBADDR=nwhcp-mongo:27017
  front-end:
    build:
      context: ../NWHCP-front_end/
      dockerfile: Dockerfile
    depends_on:
      - nwhcp-mongo
    restart: always
    ports:
      - "80:80"
